# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
# - recent_posts
# - tagcloud
# - archive

# Miscellaneous
google_analytics: UA-57476091-1
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
